name: 🧪 zunit
on: [push, pull_request, workflow_dispatch]
jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: "📡  Check out repository code"
        uses: actions/checkout@v3

      - name: "💬 Set matrix output"
        id: set-matrix
        run: |
          cd tests
          MATRIX="$(ls -1 *.zunit | sed 's/.zunit$//' | jq -ncR '{"include": [{"file": inputs}]}')"
          echo "MATRIX=${MATRIX}" >&2
          echo "::set-output name=matrix::${MATRIX}"

  zunit:
    runs-on: ubuntu-latest
    needs: build-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.build-matrix.outputs.matrix) }}

    steps:
      - name: "📡  Check out repository code"
        uses: actions/checkout@v3

      - name: "📦 Install dependencies"
        run: |
          sudo apt install -y zsh

          mkdir bin
          curl -fsSL https://raw.githubusercontent.com/molovo/revolver/v0.2.4/revolver > bin/revolver
          curl -fsSL https://raw.githubusercontent.com/molovo/color/d8f91ab5fcfceb623ae45d3333ad0e543775549c/color.zsh > bin/color

          git clone https://github.com/zunit-zsh/zunit.git zunit.git
          cd zunit.git
          git checkout b86c006f62db138a119e9be3a4b41e28876889b2
          ./build.zsh
          cd ..
          mv ./zunit.git/zunit bin

          chmod u+x bin/{color,revolver,zunit}

      - name: "🧪 zunit test: ${{ matrix.file }}"
        env:
          ZUNIT_TEST: ${{ matrix.file }}
        run: |
          echo "Running zunit test: $ZUNIT_TEST" >&2
          export PATH="$PWD/bin:$PATH"
          export TERM=xterm
          zunit --tap --verbose "tests/${ZUNIT_TEST}.zunit"
