return {
  "neovim/nvim-lspconfig",
  opts = {
    servers = {
      ansiblels = {},
      bashls = {},
      clangd = {},
      cssls = {},
      docker_compose_language_service = {},
      dockerls = {},
      gopls = {},
      html = {},
      jsonls = {},
      lemminx = {},
      lua_ls = {},
      marksman = {},
      pylsp = {},
      rust_analyzer = {},
      solargraph = {},
      terraformls = {},
      vimls = {},
      yamlls = {},
    },
  },
}
